### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
b.ndim

2

In [7]:
# Get Shape
a.shape

(3,)

In [8]:
# Get Type
a.dtype

dtype('int32')

In [10]:
# Get Size
b.itemsize

8

In [12]:
# Get total size
a.nbytes

12

In [11]:
# Get number of elements
a.size

3

In [10]:
# Getting help of a numpy array
?a

### Accessing/Changing specific elements, rows, columns, etc

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
# Get a specific element [r, c]
a[1, 5]

13

In [16]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [8]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

### Initializing Different Types of Arrays

In [18]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [19]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [20]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [21]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.19489934, 0.76111211],
       [0.03567699, 0.32529581],
       [0.56057549, 0.78398384],
       [0.868093  , 0.5131193 ]])

In [22]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 4,  0, -1],
       [ 2,  4,  5],
       [ 2,  6, -3]])

In [16]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [25]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [26]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


In [28]:
r=int(input('num of rows: '))
c=int(input('num of cols: '))
print('enter entries row wise')
entry= list(map(int, input().split(',')))
matrix=np.array(entry).reshape(r,c)
print(matrix)

num of rows: 3
num of cols: 2
enter entries row wise
23,34,23,2


ValueError: cannot reshape array of size 4 into shape (3,2)

### Mathematics

In [29]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [30]:
a + 2

array([3, 4, 5, 6])

In [31]:
a - 2

array([-1,  0,  1,  2])

In [32]:
a * 2

array([2, 4, 6, 8])

In [33]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [34]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [35]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [36]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [37]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [38]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics
```sum
prod
mean
std
var
min
max
argmin
argmax
sort```

In [39]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np.min(stats)

1

In [43]:
np.max(stats, axis=0) # 0=col

array([4, 5, 6])

In [42]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [44]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [45]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(np.hstack((h1,h2)))

print(h1)

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# `Working with Text File`

In [ ]:
data = np.loadtxt('filename.txt')
print(data)
data = np.loadtxt('filename.txt', dtype='i')
print(data)

In [68]:
# Skipping number of rows
data = np.loadtxt('filename.txt', dtype='i', skiprows=3)
print(data)
# OR
# # To skip first row
# data[1:,:]
# # To skip first column
# data[:, 1:]

[16 17 18 19 20]


In [ ]:
# Using specific columns
data = np.loadtxt('filename.txt', dtype='i', usecols=[1,3])
print(data)

In [ ]:
# Using csv files
data = np.loadtxt('filename.csv', dtype='i', delimiter=',')
print(data)

#Exercise
``` 
1. Create an array containing 7 zeros
np.zeros(5)
2. Create an array of 15 sevens
np.zeros(15)+7
OR
np.ones(15)*7
3. Create an array of integers between 5 and 15
np.arange(5,16)
4. Create an array of all the odd integers between 0 and 10
np.arange(0,10,2) + 1
OR
arr1 = np.arange(0,11) 
arr1[arr1 % 2 == 1]
5. Create 3x3 matrix from values 1 to 9
np.arange(1,10).reshape(3,3)
6. Create a 4x4 matrix from 1 to 16, and output the number 12 from it.
arr1 = np.arange(1,17).reshape(4,4)
arr1[2,3]
7. Output the first row of a matrix
arr[0]
8. Output the first column of a matrix
arr[:, 0]
OR
arr[:, 0:1]
9. Create an array of 1-9 and reverse its elements
np.arange(1,10)[::-1]
10. Select a portion of the matrix [11 12
                                    15 16]
arr1[2:, 2:]
11. Calculate the sum of all the values in the matrix
arr.sum()
12. Calculate the sum of all the rows in the matrix
arr.sum(axis=1)
13. Calculate the std deviation of a mtrix
arr.std()
14. Create an array from 11 to 20 and replace all the odd numbers with 0
15. Concatenate 2D arrays, i) Vertically  ii) Horizontally
np.vstack([v1,v2,v1,v2])
np.hstack((h1,h2))
16. Create the following numpy arrays:
a) [[4 4 4 4
    0 0 0 0
    4 4 4 4]]
arr1 = np.ones((4,4), dtype=int)*4
arr1[1:-1]=0

b) [[4 0 0 4
    4 0 0 4
    4 0 0 4]]
arr1 = np.ones((4,4), dtype=int)*4
arr1[0:,1:-1]=0

c) nola array:
    [[ 1  3  5  7  9 11 13]
    [17 19 21 23 25 27 29]
    [33 35 37 39 41 43 45]
    [49 51 53 55 57 59 61]]
nola = np.reshape(np.arange(start=1, stop=65, step=2), (4,8))
nola = nola[:, :-1]
```


